content:
  value: "<p class=\"copyright-title\">Copyright</p>\r\n\r\n<p><span>Digitální knihovnu Filozofické fakulty Masarykovy univerzity [dataset], jejímž autorem a tvůrcem je Masarykova univerzita, lze používat v souladu s licencí: Creative Commons BY 4.0.</span></p>\r\n\r\n<p><img alt=\"CC-BY-4.0\" class=\"license_icon\" src=\"/themes/islandora_muni/images/by-nc-sa.svg\" /></p>\r\n"
  format: full_html
