display:
  default:
    display_title: Nadřízené
    display_options:
      fields:
        title:
          label: Nadpis
        operations:
          label: Actions
      exposed_form:
        options:
          submit_button: Hledej
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      arguments:
        field_member_of_target_id:
          exception:
            title: Vše
  page_1:
    display_title: Stránka
