display:
  default:
    display_options:
      fields:
        title:
          label: Název
  entity_view_2:
    display_options:
      fields:
        title:
          alter:
            text: "{{ field_member_of }}\r\n<div class=\"year-volume-issue\"><div><span class=\"label\">Rok: </span>{{ field_publication_year }}</div><div><span class=\"label\">Ročník: </span>{{ field_member_of_1 }}</div><div><span class=\"label\">Číslo: </span>{{ title }}</div></div>"
  entity_view_3:
    display_options:
      fields:
        title:
          alter:
            text: "{{ field_member_of }}\r\n<div class=\"year-volume-issue\"><div><span class=\"label\">Rok: </span>{{ field_years }}</div><div><span class=\"label\">Ročník: </span>{{ title }}</div>"
