label: Komentáře
display:
  default:
    display_title: Výchozí
    display_options:
      title: Komentáře
      fields:
        comment_bulk_form:
          action_title: Akce
        subject:
          label: Předmět
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Autor
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operace
        name_1:
          separator: ', '
      pager:
        options:
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        subject:
          expose:
            label: Předmět
        langcode:
          expose:
            label: Jazyk
  page_published:
    display_options:
      menu:
        title: Komentáře
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Akce
        subject:
          label: Předmět
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Autor
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operace
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: Předmět
        langcode:
          expose:
            label: Jazyk
