label: Média
display:
  default:
    display_title: Výchozí
    display_options:
      title: Média
      fields:
        media_bulk_form:
          action_title: Akce
        thumbnail__target_id:
          label: Náhled
        bundle:
          label: Typ
        uid:
          label: Autor
        status:
          label: Stav
        operations:
          label: Operace
      pager:
        options:
          tags:
            next: 'Následující ›'
            previous: '‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      exposed_form:
        options:
          submit_button: Filtr
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        bundle:
          expose:
            label: Typ
        langcode:
          expose:
            label: Jazyk
  media_page_list:
    display_title: Média
    display_options:
      menu:
        title: Média
