display:
  default:
    display_title: Výchozí
    display_options:
      fields:
        changed:
          separator: ', '
      exposed_form:
        options:
          submit_button: Hledej
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
