label: Obsah
display:
  default:
    display_title: Výchozí
    display_options:
      title: Obsah
      fields:
        title:
          label: Nadpis
        type:
          label: 'Typ obsahu'
        name:
          label: Autor
        status:
          label: Stav
        operations:
          label: Operace
      pager:
        options:
          tags:
            next: 'Následující ›'
            previous: '‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
      exposed_form:
        options:
          submit_button: Filtr
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      filters:
        title:
          expose:
            label: Nadpis
        type:
          expose:
            label: 'Typ obsahu'
        status:
          expose:
            label: Stav
        langcode:
          expose:
            label: Jazyk
  page_1:
    display_title: Stránka
    display_options:
      menu:
        title: Obsah
      tab_options:
        title: Obsah
