display:
  default:
    display_options:
      exposed_form:
        options:
          exposed_sorts_label: 'Ročníky, čísla'
          bef:
            sort:
              advanced:
                combine_rewrite: "Years Desc|Od nejnovějších\r\nYears Asc|Od nejstarších\r\n"
      fields:
        title:
          alter:
            text: "{% if field_virtual == '1' and nid_1 is not empty %}\r\n  <em><a href='/cs/node/{{ nid_1 }}'>{{ title }}</a></em>\r\n{% else %}\r\n  <a href='/cs/node/{{ nid }}'>{{ title }}</a>\r\n{% endif %}"
        title_1:
          alter:
            text: '{{ field_years }}  (Ročník {{ title_1 }}{{ field_category }})'
        field_category:
          alter:
            text: '{% if field_category == ''spffbu'' %} edice SPFFBU{% endif %}'
