display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Hledej
          reset_button_label: Reset
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          tags:
            previous: '‹ Předchozí'
            next: 'Následující ›'
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      fields:
        filename:
          separator: ', '
        fid:
          label: 'ID souboru'
          separator: ', '
  page_1:
    display_options:
      menu:
        title: Seznam
      fields:
        filename:
          separator: ', '
        fid:
          label: 'ID souboru'
          separator: ', '
        filename_1:
          label: 'Název souboru'
          separator: ', '
  page_2:
    display_options:
      fields:
        filename:
          separator: ', '
        fid:
          label: 'ID souboru'
          separator: ', '
