display:
  default:
    display_options:
      header:
        result:
          content: "<em>Zobrazují se záznamy @start - @end z celkového počtu @total.</em>\r\n<br><br>"
      pager:
        options:
          expose:
            items_per_page_label: 'Výsledků na stránku'
      exposed_form:
        options:
          exposed_sorts_label: 'Seřadit záznamy dle'
          bef:
            sort:
              advanced:
                combine_rewrite: "Title Asc|Název (vzestupně)\r\nTitle Desc|Název (sestupně)\r\nPublication year Asc|Od nejstarších\r\nPublication year Desc|Od nejnovějších\r\n"
      filters:
        type:
          expose:
            label: 'Typ dokumentu'
      fields:
        field_pagination_from:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        nothing:
          alter:
            text: "{% if type_1|striptags == 'serial' %}\r\n  <span><em>{{ title }}</em></span><span>{{ field_publication_year_from }}–{{ field_publication_year_to }}</span>\r\n{% elseif type_1|striptags == 'article' %}\r\n  <span>{{ nothing_2 }}</span><span>{{ title }}</span><span>{{ field_member_of_2 }}{{ aggregated_field_published }}, roč. {{ field_member_of_1 }}, č. {{ field_member_of }}, s. {{ field_pagination_from }}{{second}}.</span>\r\n{% elseif type_1|striptags == 'book' %}\r\n  <span>{{ nothing_2 }}</span><span><em>{{ title }}</em></span><span>{{ field_publication_year_text }}</span>\r\n{% elseif type_1|striptags == 'chapter' %}\r\n  <span>{{ nothing_2 }}</span><span>{{ title }}</span><span>{{ nothing_1 }} {{ field_publication_year_text_1 }}, s. {{ field_pagination_from }}{{second}}.</span>\r\n{% elseif type_1|striptags == 'book_series' %}\r\n  <span><em>{{ title }}</em></span><span>{{ field_publication_year_from }}–{{ field_publication_year_to }}</span>\r\n{% elseif type_1|striptags == 'issue' %}\r\n  <span><em>{{ title }}</em></span>\r\n{% endif %}"
