display:
  default:
    display_options:
      title: 'Rozšířené vyhledávání'
      exposed_form:
        options:
          submit_button: Hledej
          exposed_sorts_label: 'Seřadit záznamy dle'
          bef:
            sort:
              advanced:
                combine_rewrite: "Relevance Asc|Relevance (vzestupně)\r\nRelevance Desc|Relevance (sestupně)\r\nTitle Asc|Název (vzestupně)\r\nTitle Desc|Název (sestupně)\r\nAuthor Asc|Autor (vzestupně)\r\nAuthor Desc|Autor (sestupně)\r\nPublication year Asc|Rok vydání (vzestupně)\r\nPublication year Desc|Rok vydání (sestupně)"
            filter:
              field_department_mu:
                advanced:
                  rewrite:
                    filter_rewrite_values: "- Všechny -|- Všechny -\r\nCentrum asijských studií|Centrum asijských studií\r\nHistorický ústav|Historický ústav\r\nKatedra anglistiky a amerikanistiky|Katedra anglistiky a amerikanistiky\r\nKatedra divadelních studií|Katedra divadelních studií\r\nKatedra filozofie|Katedra filozofie\r\nKatedra informačních studií a knihovnictví|Katedra informačních studií a knihovnictví\r\n[Katedra politologie (aktuálně FSS MU)]|[Katedra politologie (aktuálně FSS MU)]\r\n[Katedra sociologie (aktuálně FSS MU)]|[Katedra sociologie (aktuálně FSS MU)]\r\nPsychologický ústav|Psychologický ústav\r\nSeminář dějin umění|Seminář dějin umění\r\nSeminář estetiky|Seminář estetiky\r\nÚstav archeologie a muzeologie|Ústav archeologie a muzeologie\r\nÚstav české literatury|Ústav české literatury\r\nÚstav českého jazyka|Ústav českého jazyka\r\nÚstav evropské etnologie|Ústav evropské etnologie\r\nÚstav filmu a audiovizuální kultury|Ústav filmu a audiovizuální kultury\r\nÚstav germanistiky, nordistiky a nederlandistiky|Ústav germanistiky, nordistiky a nederlandistiky\r\nÚstav hudební vědy|Ústav hudební vědy\r\nÚstav jazykovědy a baltistiky|Ústav jazykovědy a baltistiky\r\nÚstav klasických studií|Ústav klasických studií\r\nÚstav pedagogických věd|Ústav pedagogických věd\r\nÚstav pomocných věd historických a archivnictví|Ústav pomocných věd historických a archivnictví\r\nÚstav religionistiky|Ústav religionistiky\r\nÚstav románských jazyků a literatur|Ústav románských jazyků a literatur\r\nÚstav slavistiky|Ústav slavistiky"
          reset_button_label: Vymaž
      pager:
        options:
          tags:
            next: 'Další ››'
            previous: '‹‹ Předchozí'
            first: '« První'
            last: 'Poslední »'
          expose:
            items_per_page_label: 'Výsledků na stránku'
      header:
        result:
          content: "Zobrazují se záznamy @start - @end z celkového počtu @total\r\n<br><br>"
      filters:
        search_api_fulltext_1:
          expose:
            label: 'Libovolný výraz'
            description: 'Vyhledává v celé databázi.'
        search_api_fulltext:
          expose:
            label: 'Libovolný výraz z popisu dokumentů'
            description: 'Vyhledává pouze v záznamech (metadatech) dokumentů.'
          admin_label: 'Klíčové slovo (metadata)'
        search_api_fulltext_2:
          expose:
            label: Název
        field_topic:
          expose:
            label: Obor
        type:
          expose:
            label: 'Typ dokumentu'
            description: 'Zvolíte-li „stať“, vyhledáváte v časopiseckých článcích, sborníkových příspěvcích a kapitolách monografií.'
          group_info:
            label: 'Typ dokumentu'
            group_items:
              1:
                title: Stať
              2:
                title: 'Knižní edice'
              3:
                title: Kniha
              4:
                title: Seriál
              5:
                title: Číslo
              6:
                title: Článek
            description: 'Zvolíte-li „stať“, vyhledáváte v časopiseckých článcích, sborníkových příspěvcích a kapitolách monografií.'
        aggregated_field_published_to:
          expose:
            label: 'Rok vydání (od)'
        field_language:
          expose:
            label: Jazyk
        aggregated_field_subject:
          expose:
            label: Téma
        field_department_mu:
          expose:
            label: 'Ústav FF MU'
        aggregated_field_published:
          expose:
            label: 'Rok vydání (do)'
        author_names:
          expose:
            label: Autor
            description: 'Autor nebo další původce dokumentu (editor, překladatel aj.).'
      fields:
        nid:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        title:
          alter:
            text: '<a href="/cs/node/{{ nid }}">{{ title }}.</a> '
        field_pagination_from:
          fallback_options:
            format_plural_string: !!binary MQNAY291bnQD
        nothing:
          alter:
            text: "{% if type_1|striptags == 'serial' %}\r\n  <em>{{ title }}</em>{{ field_publication_year_from }}–{{ field_publication_year_to }}\r\n{% elseif type_1|striptags == 'article' %}\r\n  {{ nothing_2 }}{{ title }}<em>{{ field_member_of_2 }}</em>{{ aggregated_field_published }}, roč. {{ field_member_of_1 }}, č. {{ field_member_of }}, s. {{ field_pagination_from }}{{second}}.\r\n{% elseif type_1|striptags == 'book' %}\r\n  {{ nothing_2 }}<em>{{ title }}</em>{{ field_publication_year_text }}\r\n{% elseif type_1|striptags == 'chapter' %}\r\n  {{ nothing_2 }}{{ title }}{{ nothing_1 }} {{ field_publication_year_text_1 }}, s. {{ field_pagination_from }}{{second}}.\r\n{% elseif type_1|striptags == 'book_series' %}\r\n  <em>{{ title }}</em>{{ field_publication_year_from }}–{{ field_publication_year_to }}\r\n{% elseif type_1|striptags == 'issue' %}\r\n  <em>{{ field_member_of_1_1 }}, {{ aggregated_field_published }}, vol. {{ field_member_of_3 }}, issue {{ title }}</em>\r\n{% endif %}"
  page_1:
    display_options:
      header:
        result:
          content: "Zobrazují se záznamy @start - @end z celkového počtu @total\r\n<br><br>"
      menu:
        title: Vyhledávání
    display_title: Základní
