display:
  default:
    display_title: Nadřízené
    display_options:
      exposed_form:
        options:
          submit_button: Hledej
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
      pager:
        options:
          expose:
            items_per_page_label: 'Položek na stránku'
            items_per_page_options_all_label: '- Vše -'
            offset_label: Posun
      fields:
        name:
          label: Jméno
      arguments:
        field_media_of_target_id:
          exception:
            title: Vše
  page_1:
    display_title: Stránka
    display_options:
      menu:
        title: Média
      fields:
        media_bulk_form:
          action_title: Akce
        name:
          label: Jméno
  rest_export_1:
    display_options:
      fields:
        name:
          label: Jméno
