display:
  default:
    display_title: Výchozí
    display_options:
      exposed_form:
        options:
          submit_button: Hledej
          exposed_sorts_label: 'Řadit dle'
          sort_asc_label: Vzestupně
          sort_desc_label: Sestupně
  block_1:
    display_options:
      block_category: Uživatel
