_core:
  default_config_hash: bzVgxAW8qL_RR1YMiABMUohoPHQnkYmISP5yyKAF0Qc
rest_oai_pmh:
  entity_type: node
view_displays:
  'oai_pmh:entity_reference_1': 'oai_pmh:entity_reference_1'
  'oai_pmh:entity_reference_2': 'oai_pmh:entity_reference_2'
  'oai_pmh:entity_reference_3': 'oai_pmh:entity_reference_3'
support_sets: 1
mapping_source: rdf
repository_name: 'Digital Library of Faculty of Arts of Masaryk University'
repository_email: kic_admins@ics.muni.cz
expiration: '3600'
metadata_map_plugins:
  -
    label: mods
    value: ''
  -
    label: oai_dc
    value: dublin_core_metatag
  -
    label: oai_raw
    value: ''
cache_technique: liberal_cache
mods_view:
  view_machine_name: ''
  view_display_name: ''
