_core:
  default_config_hash: ByOVf1cU9r5NkZ4ieBJ7k9sUid6jb03ojMN1gjJ0-OU
site_key: 6Leo6pkpAAAAALK_peLI-PJYVxrX9pS5bNvYkIRf
secret_key: 6Leo6pkpAAAAAD_gfxWD-abfTD4gitCt_N5Nljbe
verify_hostname: false
use_globally: false
widget:
  theme: light
  type: image
  size: ''
  noscript: false
