links:
  -
    path: /
    priority: '1.0'
    changefreq: daily
  -
    path: /about
    priority: '1.0'
    changefreq: monthly
  -
    path: /documentation
    priority: '1.0'
    changefreq: monthly
  -
    path: /help
    priority: '1.0'
    changefreq: monthly
