display:
  default:
    display_options:
      fields:
        nothing:
          alter:
            text: '{% if field_rights_access == ''plný text nepřístupný'' %}closed{% elseif field_rights_access == ''přístupné po uplynutí embarga'' and field_embargo_end_date > "now"|date("U")  %}closed{% else %}open{% endif %}'
        title:
          alter:
            text: '<a href="cs/node/{{ nid }}">{{ title }}</a>'
            path: 'cs/node/{{ nid }}'
