display:
  default:
    display_options:
      fields:
        field_member_of:
          label: 'Zdrojový dokument'
  entity_view_2:
    display_options:
      fields:
        nothing_2:
          alter:
            text: '<strong>Zdrojový dokument: </strong>'
