force: 1
delete_textarea: '23943'
actions: null
form_build_id: form-jZPjJT9lIJYeMgH_orkO-Bc_3uOgp8fyZXVm66GGaDU
form_token: xqmbPwxB_SRF7CnfoBEBOsngxp_hy6BhwKdIKvDejkU
form_id: fancy_file_delete_manual
field_handle: null
searched_fields: null
