entity_type_groups:
  node:
    article:
      google_scholar: google_scholar
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
    book:
      open_graph: open_graph
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
    serial:
      dublin_core: dublin_core
      dublin_core_advanced: dublin_core_advanced
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_og_description: null
  metatag_maxlength_dcterms_title: null
  metatag_maxlength_dcterms_description: null
tag_scroll_max_height: ''
tag_trim_end: '|.,-:;/+&([{"'''
