content:
  value: '<p class="copyright-title">Copyright</p><p><span>Digitální knihovnu Filozofické fakulty Masarykovy univerzity [dataset], jejímž autorem a tvůrcem je Masarykova univerzita, lze používat v souladu s licencí: Creative Commons BY 4.0.</span></p><p><img class="license_icon" src="/themes/custom/islandora_muni/images/by.svg" alt="CC-BY-4.0" width="120" height="42"></p>'
  format: full_html
