content:
  value: "<p><a class=\"site-branding__logo\" href=\"/cs\" rel=\"home\"><img alt=\"Home\" src=\"/themes/custom/islandora_muni/platform_specific/images/logo-cs.svg\" /> </a></p>\r\n"
  format: full_html
