display:
  default:
    display_options:
      fields:
        field_url_publications:
          alter:
            text: 'Další publikační činnost členů ústavu'
      header:
        area:
          content:
            value: ''
            format: basic_html
