_core:
  default_config_hash: XgeYJpPmZIOwE_nA73tYvFw-Rcj-HtlbNwfktqSVsaQ
broker_url: 'tcp://localhost:61613'
jwt_expiry: '+2 hour'
upload_form_location: 'fedora://pdf'
upload_form_allowed_mimetypes: 'pdf txt jpg png xml'
gemini_url: ''
gemini_pseudo_bundles:
  'islandora_object:node': 'islandora_object:node'
redirect_after_media_save: false
delete_media_and_files: true
